.\" Process this file with groff -man -Tascii techne.1
.\"
.TH TECHNE 1 "November 2010" Linux
.SH NAME
techne \- A general purpose, programmable physical simulator and renderer.
.SH SYNOPSIS
.BI "techne [" OPTION... ]
.SH DESCRIPTION
.B Techne
is a general purpose, programmable physical simulator and renderer.
It reads in a set of scripts wherein every aspect of a physical system
is specified and then proceeds to simulate and render the system
onscreen.
.SH OPTIONS
.TP
.B "-h, --help"
Display a help message.
.TP
.BI "-c " FILE ", --configuration" =FILE
Include
.I FILE
into the list of sources that are going to be executed by
Techne at start up.  Multiple
.B -c
options can be used to specify any number of source files.
.TP
.BI "-O " "OPTION[=VALUE]" ", --option " "OPTION[=VALUE]"
Define an option with name
.I OPTION
and value
.I VALUE.
The meaning of the option itself depends on the executed program,
Techne simply defines it.  If
.I VALUE
is left out it defaults to "true".  Multiple
.B -O
switches can be specified.  If more than one
.B -O
switches specify the same option the value of the option is set to a
table of all specified values.
.TP
.BI "-e " "STAT" ", --execute" "=STAT"
This option behaves as if a file containing the text 
.I STAT
which should comprise valid Lua statements had been specified via the 
.B -c
option, that is the statements will be compiled and added to the list
of sources to run upon startup.


.TP
.BI "-l " "MODULE" ", --load" "=MODULE"
Request the module with name
.I MODULE
to be loaded at startup.

.TP
.BI "-l " "always|never|auto" ", --load" "=always|never|auto"
Specify when to color console output.  Always and never have the
obvious meaning while auto tries to guess if color is welcome based on
wether the output has been redirected or not.

.TP
.B -a , --load-all
Request all known modules to be loaded at startup.

.TP
.B -i , --interactive
Drop to an interactive command prompt after initialization.

.TP
.B -q , --quiet
Suppress the output of cosnole messages.  This switch can be specified
multiple times to increase the level of suppression.

.P
There are a few options that can be specified through the 
.B -O
switch that are interpreted by Techne itself.  Of use to the end user might be:
.TP
.B mute
Disable audio rendering.
.TP
.B name , class
Specify the application window's WM_CLASS property.  This options
helps the window manager identify which application name and icon to
use for this window.  Usually if the application's name is Foo and
there is a foo.desktop file installed the name should be set to `foo'
and class to `Foo'.
.SH BUGS
Please report any bugs you find on the techne-devel mailing list or use the bug tracker in Techne's project page <http://savannah.nongnu.org/projects/techne>.
.SH AUTHOR
Dimitris Papavasiliou <dpapavas at gmail dot com>
.SH "SEE ALSO"
.BR techne-browser (1),
.BR billiards (6),
.BR aviation (6),
.BR airrace (6),
