#!/bin/bash

prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
datarootdir=${prefix}/share
datadir=${datarootdir}
debug=""

# Run through the list of arguments given
# and extract the ones that should be handled
# at this point.

args=""

while [ -n "$1" ]; do
    if [ $1 = "--debug" ]; then
	debug="gdb --args"
    else
	args="$args $1"
    fi
    
    shift
done

${debug} ${libdir}/techne/techne.bin -Oprefix=${datadir}/techne $args
